
package com.bansi.remote.webservice.client.wsimport.fisrtwebserviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FisrtWebServiceImpl", targetNamespace = "http://impl.server.webservice.remote.bansi.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface FisrtWebServiceImpl {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAddressByPhoneNo", targetNamespace = "http://impl.server.webservice.remote.bansi.com/", className = "com.bansi.remote.webservice.server.impl.GetAddressByPhoneNo")
	@ResponseWrapper(localName = "getAddressByPhoneNoResponse", targetNamespace = "http://impl.server.webservice.remote.bansi.com/", className = "com.bansi.remote.webservice.server.impl.GetAddressByPhoneNoResponse")
	@Action(input = "http://impl.server.webservice.remote.bansi.com/FisrtWebServiceImpl/getAddressByPhoneNoRequest", output = "http://impl.server.webservice.remote.bansi.com/FisrtWebServiceImpl/getAddressByPhoneNoResponse")
	public String getAddressByPhoneNo(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
